publish:
  image: salesadriano/docker_publisher
  stage: build
  services:
    - docker:dind
  before_script: 
      - /start.sh
      - sleep 5
  script:
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - git remote -v show
    #- docker build . -t testes --pull
    #- docker push $TAG_COMMIT
    #- docker push $TAG_LATEST
