publish:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker ps
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    #- docker push $TAG_COMMIT
    #- docker push $TAG_LATEST
