publish:
  image: salesadriano/docker_publisher
  stage: build
  services:
    - docker:dind
  before_script: 
      - service docker start
      - sleep 5
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $CI_REGISTRY/$CI_REGISTRY_USER/docker_publisher --pull
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/docker_publisher
  only:
    - master
