stages:
  - build

build:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_PATH/docker" .
    - docker push "$CI_REGISTRY_PATH/docker"
  only:
   - teste


stages:          # List of stages for jobs, and their order of execution
  - build
