publish:
  image: salesadriano/docker_publisher
  stage: build
  services:
    - docker:dind
  before_script: 
      - /start.sh
  script:
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - dockerd
    #- docker push $TAG_COMMIT
    #- docker push $TAG_LATEST
